# Generated by Django 5.2.1 on 2025-06-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_used',
            field=models.CharField(blank=True, null=True),
        ),
    ]
