# Generated by Django 5.2.1 on 2025-06-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_alter_user_otp_alter_user_otp_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
