# Generated by Django 5.2.1 on 2025-06-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0003_alter_plan_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(),
        ),
    ]
