# Generated by Django 5.2.1 on 2025-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0007_subscription_pending_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='backoffice_engine/user_generated_image'),
        ),
    ]
