# Generated by Django 5.2.1 on 2025-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0008_alter_generated_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggested_prompt',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
